In [1]:
#modul numpy
import numpy as np

In [2]:
# n rozmerne pole
u=np.array([1,0,-1])

In [3]:
type(u)

numpy.ndarray

In [4]:
u

array([ 1,  0, -1])

In [5]:
v=np.array([2,1,0],dtype = 'float')

In [6]:
u*v

array([ 2.,  0., -0.])

In [7]:
u@v

2.0

In [95]:
m = np.array([[2,1,0],[1,2,3]],dtype = 'float')

In [11]:
m@m.transpose()

array([[ 5.,  4.],
       [ 4., 14.]])

In [13]:
m.shape

(2, 3)

In [14]:
m.size

6

In [19]:
#generatory pola(ones,zeros,eye,arange,linspace)
np.ones((5,5),dtype = 'bool')

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.eye(8,k=2,dtype='int')

array([[0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [35]:
np.reshape(np.arange(1,25),(4,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [37]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [42]:
#random numpy.random
import numpy.random as npr
npr.rand(5)

array([0.21227274, 0.51993597, 0.68091115, 0.41706977, 0.24022542])

In [50]:
npr.randint(1,6+1)

3

In [65]:
npr.choice(npr.randint(1,7),size=10,p=(0.01,0.01,0.01,0.01,0.01,0.95))

ValueError: 'a' and 'p' must have same size

In [66]:
a = np.arange(1,7)
print(a)
npr.shuffle(a)
print(a)

[1 2 3 4 5 6]
[1 3 6 2 5 4]


In [70]:
#nacitanie pola zo suboru /loadtxt
p13=np.loadtxt('E13.txt',dtype = 'float')

In [71]:
p13[2]

7.432498619952474e+49

In [72]:
sum(p13)

5.537376230390877e+51

In [75]:
np.savetxt('vysledok.txt',p13,fmt='%i')

In [77]:
m=npr.rand(1000,1000)

In [78]:
m

array([[0.98297124, 0.31761606, 0.30132677, ..., 0.30463151, 0.55539554,
        0.3070955 ],
       [0.92170945, 0.23296462, 0.94680109, ..., 0.33893312, 0.52491345,
        0.85260272],
       [0.91592163, 0.01678358, 0.32209593, ..., 0.77887942, 0.11202023,
        0.16970768],
       ...,
       [0.6776704 , 0.05138393, 0.3886305 , ..., 0.61005223, 0.07542409,
        0.96507701],
       [0.57285742, 0.72604128, 0.7415143 , ..., 0.32214226, 0.54031688,
        0.9071095 ],
       [0.79211331, 0.58114106, 0.65237248, ..., 0.021561  , 0.06367317,
        0.13867241]])

In [79]:
m.size

1000000

In [80]:
np.savetxt('M1000.txt',m)

In [82]:
np.save('M1000',m)

In [ ]:
ls

In [ ]:
ls -l

In [85]:
%time b = np.load('M1000.npy')
%time b = np.loadtxt('M1000.txt')

CPU times: user 0 ns, sys: 9.99 ms, total: 9.99 ms
Wall time: 10.6 ms
CPU times: user 512 ms, sys: 14.9 ms, total: 527 ms
Wall time: 548 ms


In [86]:
t = [i/10 for i in range(1,100,10)]
t

[0.1, 1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1]

In [87]:
from math import sin

In [92]:
t=np.arange(1,100,10)/10
t

array([0.1, 1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1])

In [93]:
np.sin(t)

array([ 0.09983342,  0.89120736,  0.86320937,  0.04158066, -0.81827711,
       -0.92581468, -0.1821625 ,  0.72896904,  0.96988981,  0.31909836])

In [96]:
m[:,0]

array([2., 1.])

In [97]:
#maskovanie
m>3

array([[False, False, False],
       [False, False, False]])

In [100]:
m>2

array([[False, False, False],
       [False, False, False]])

In [99]:
m[m>2]=0

#polynomy 
$p_1 = x^5-3x^3+4x-11$
$p_2 = x^2-3x+2$

In [108]:
p1 = np.array([1,0,-3,0,4,-11])
p2 = np.array([1,-3,2])
print(p1)
print(p2)

[  1   0  -3   0   4 -11]
[ 1 -3  2]


In [110]:
np.polyval(p2,10)

72

In [111]:
np.polyadd(p1,p2)

array([ 1,  0, -3,  1,  1, -9])

In [112]:
np.polydiv(p2,np.array([1,-2]))

(array([ 1., -1.]), array([0.]))

In [113]:
np.polydiv(p1,p2)

(array([1., 3., 4., 6.]), array([ 14., -23.]))

$x^3+3x^2+4x+6+\frac{14x-23}{x^2-3x+2}$

In [114]:
np.polyder(p1)

array([ 5,  0, -9,  0,  4])

In [115]:
import numpy.linalg as la

In [125]:
a = np.array([[1,1,1],[1,2,4],[2,-3,-1]])
b = np.array([4,12,4])
x = la.solve(a,b)

In [128]:
a@x==b

array([[False],
       [ True],
       [False]])

In [129]:
a@x-b

array([[-8.8817842e-16],
       [ 0.0000000e+00],
       [-4.4408921e-16]])